<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $user common\models\User */

$userlink = \yii\helpers\Url::to(["user/view", "id" => $user->id]);
$tournamentlink = \yii\helpers\Url::to(["tournament/index"]);
$support = Yii::$app->params["supportEmail"];
?>

Hello <?= Html::encode($user->name) ?>,

This is an automated e-mail that was generated by <?= Html::a(Yii::$app->params["appName"], Yii::$app->params["appUrl"]) ?>.

A new user account has been created for you with the following credentials:

Username: <?= $user->username ?>
Password: <?= $user->password ?>

Please login and fill the remaining fields of your profile (and change your password) at:
<?= Html::a(Html::encode($userlink), $userlink) ?>

After that you may wanna take a look at the current tournaments at:
<?= Html::a(Html::encode($tournamentlink), $tournamentlink) ?>

If you have any question please feel free to write to your support team at:
<?= Html::a(Html::encode($support), "mailto:" . $support) ?>

Best
The <?= Yii::$app->params["appName"] ?> Team