<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $user common\models\User */

$userlink = \yii\helpers\Url::to(["user/view", "id" => $user->id], true);
$tournamentlink = \yii\helpers\Url::to(["tournament/index"], true);
$support = Yii::$app->params["supportEmail"];
?>

Hi <?= Html::encode($user->givenname) ?>,<br>
<br>
This is an automated e-mail that was generated by <?= Html::a(Yii::$app->params["appName"], Yii::$app->params["appUrl"]) ?>.
<br>
<br>
A new user account has been created for you with the following credentials:<br>
Username/Email: <?= $user->email ?><br>
Temporary Password: <?= $user->password ?><br>
<br>
Please login and fill the remaining fields of your profile (and change your password) at:<br>
<?= Html::a(Html::encode($userlink), $userlink) ?><br>
<br>
After that you may wanna take a look at the current tournaments at:<br>
<?= Html::a(Html::encode($tournamentlink), $tournamentlink) ?><br>
<br>
If you have any question please feel free to write to your support team at:<br>
<?= Html::mailto(Html::encode($support), $support) ?><br>
<br>
Best<br>
The <?= Yii::$app->params["appName"] ?> Team<br>